ghostmkg/programming-language

comparing_number.py

Added Python code for comparing 2 number using if-else statment

Comparing two number

---

photo_cartonizer.py
speed.py
web_bot.py

This pull request introduces a new script in `web_bot.py` to automate a web search using Selenium.

feat:  creating web-bot using selenium 

---

Cube_3D/index.html
Cube_3D/style.css
bot_friend.py

Description: This PR introduces a simple command-line chatbot implemented in Python utilizing the OpenAI API. The chatbot can engage in conversation and responds to user inputs until the user types "exit." Key features include:

feat: A terminal based chatbot

---

Stock_Buy_Sell.java

Leetcode problem it will help  in interview

Stock_Buy_Sell java code

---

a_star_algorithm.py

Explanation:
1. Graph Representation: The graph is represented as an adjacency list where each node maps to a list of tuples. Each tuple contains a neighboring node and the cost to reach that neighbor.
2. Priority Queue: The algorithm uses a priority queue (open_list) to keep track of nodes to explore, prioritizing the node with the smallest f(n) = g(n) + h(n).
3. Heuristic Function: The heuristic() function provides an estimated cost to reach the goal from any given node. In this case, a simple dictionary is used, which can be adjusted depending on the problem (e.g., Euclidean or Manhattan distances).
4. Algorithm Logic:
The algorithm starts by initializing the priority queue with the start node and its heuristic value.
It pops the node with the lowest f(n) from the queue.
If the goal is …

Contribution for Hackertoberfest2024 : a_star_algorithm.py

---

Topological-sort.cpp

Implementation of Topological Sort in c++.

Implementation of Topological Sort

---

TicTacToe.py

This project is a simple implementation of the classic Tic-Tac-Toe game using Python's Tkinter library for the graphical user interface. The game is designed for two players, "X" and "O", who take turns marking the spaces in a 3x3 grid. The goal is to be the first player to get three of their marks in a horizontal, vertical, or diagonal row. 
Features:
User-friendly interface: A clean and intuitive layout using Tkinter.
Real-time gameplay: Players can click on the grid to place their mark.
Winner announcement: The game highlights the winning row, column, or diagonal in yellow and announces the winner.
Restart functionality: A restart button allows players to start a new game without closing the window.
Tie detection: The game correctly handles ties when all spaces are filled with no …

A GUI based TicTacToe Game

---

age_validator.py

**Age Validator**
A simple Python program that checks if the user's input age meets specific conditions:
>If the age is 18 or above, it confirms the user is above the age of consent.
>If the age is less than or equal to 0, it flags it as an invalid input.
>If the age is below 18, it notifies the user accordingly.
The program runs in an infinite loop, continuously asking for user input until manually stopped.

Age Validator Python Program

---

simple_text_editor.py

Added a Simple Text Editor using Python and Tkinter
This pull request adds a basic **Text Editor** application built using **Python** and the **Tkinter** library. The text editor allows users to:
- **Open files**: Supports `.txt`, `.py`, and `.cpp` files.
- **Edit text**: Users can modify the text within the text editor interface.
- **Save files**: Supports saving the modified text back to `.txt`, `.py`, and `.cpp` file formats.
- **Keyboard Shortcuts**: 
- `Ctrl + S` to save files.
- `Ctrl + O` to open files.
This addition can serve as a simple utility for opening, editing, and saving text files directly from the GUI. It also demonstrates basic usage of the Tkinter library for creating GUI-based Python applications.

Added a Simple Text Editor using Python and Tkinter

---

Cube_3D/dice roller.py

Newupdate dice roll

---

InstagramProofileExtracter.py
weatherApplication.py

This pull request introduces the first version of a Weather Application that allows users to fetch and log weather information for any city using the OpenWeatherMap API.
Key features:
User Input for City: Users can input the name of any city to get the latest weather details.
Real-Time Weather Data: The app retrieves the current weather conditions such as temperature, wind speed, humidity, and weather description for the specified city.
Sunrise & Sunset Times: Provides users with accurate sunrise and sunset timings for the city.
Coordinate Information: Displays the latitude and longitude of the city.
Data Logging: Automatically saves the weather details into a text file, allowing users to keep a record of the data for future reference.
Error Handling: Detects invalid city inputs and …

Weather Application with City Weather Data Logging

---

MegabyteConverter.java

// Write a method called printMegabytesAndKiloBytes that has 1 parameter of type int with the name kiloBytes.
// 
// The method should not return anything (void) ans it nees to calculate the megabytes and remaining kilobytes from the kilobytes parameter.
//
// Then it needs to print a message in the format "XX KB = YY MB and ZZ KB".
//
// XX represents kiloBytes
// YY represents megabytes
// ZZ represents remaining kilobytes
//
// for example when the parameter kilobytes is 2500 it needs to print "2500 KB = 2 MB and 452 KB"
// if the parameter kiloBytes is less than 0 then print the text "Invalid Value"
//
// TIP : Use remainder operator
// TIP : Do not set kilobytes parameter value inside your method.

Added Solution for Megabyte Converter for Most Famous Java Course of Tim Buchalka

---

Armstrong.java
Emirp.java
Pal_Prime.java
Perfect.java
Spy_Recur.java
TwinPrime.java

Hello,
the following java programs added-
1.  Check for emirp number
2.  Check for Armstrong number
3.  Check for number which is both palindrome and prime
4.  Check for Perfect number
5.  Check for Spy number using recursion
6.  Check for TwinPrime numbers
Please review them.
Thanks !

Added java programs

---

KnapsackProblem.py

Implementation of the 0/1 Knapsack Problem using dynamic programming

Added Knapsack problem dynamic programming

---

library Management.py
reverse string & paliondrome.py

I have pushed a code for a library manager in python cli.

Added Library Management Code

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md

According to #37 issue (Your repo should follow Hacktoberfest 2024 Guidelines 📝), I am adding the necessary files to your repository.
Accept this PR to make your repo remarkable.

📝 Making your repo perfecto for Hacktoberfest 2024

---

bubblesort.py

sorts the given array using bubble sort

bubblesort.py

---

paliandrome.js

paliandrome javascript function

paliandrome javascript

---

primeNumber.js

- Add prime number with generating javascript function

feat(PrimeNuber): add prime-number wit javaScript function

---

CoinChangeProblem.py

Adding Coin Change Problem

---

deletion and reverse in circular linked list.cpp

Given a Circular Linked List. The task is to delete the given node, key in the circular linked list, and reverse the circular linked list.
Examples:
Input: Linked List: 2->5->7->8->10, key = 8
Output: 10->7->5->2 
Explanation: After deleting 8 from the given circular linked list, it has elements as 2, 5, 7, 10. Now, reversing this list will result in 10, 7, 5, 2 & the resultant list is also circular.
Yes

circular linked list

---

.vscode/launch.json
Leetcode_1963.java

This is a Java solution of Leetcode problem number 1963

Leetcode 1963

---

Color Mind Challenge

This pull request introduces **Color Mind Challenge**, an interactive and fast-paced color-typing game built using Python's Tkinter. The game challenges players to type the color of the word displayed, not the actual text. Key features include:
- Countdown timer starting at 30 seconds.
- Randomly shuffled color names and texts for each round.
- Instant score updates based on correct inputs.
- Simple and clean GUI for an engaging user experience.
This game is fun, educational, and helps improve focus and typing skills under pressure!

Create Color Mind Challenge

---

calculator.c

Added a C program to implement a simple calculator

---

rock-paper-scissors.py

Here is how a simple Python program implementing the game of Rock, Paper, Scissors can be expressed in one line. A user is allowed to input his choice, while the computer will randomly choose one of the three options. The computer then determines and declares a winner by comparing the user's choice and that of the computer; after all, standard rules for the game declare that Rock beats Scissors, Scissors beats Paper, and Paper beats Rock. The game will output the choices and the result (win, lose, or tie) if both happen to choose the same.

rock-paper-scissors-game

---

Floyd_warshall.c

This is a C program for implementing Floyd Warshall Algorithm
code not changed
no
yes

Added  Floyd warshall Algorithm in C language

---

binarytree.java
hello.c++

Binarytree

---

hello.c++

add hello world and add two number

---

.vscode/launch.json
Leetcode_1813.java
Leetcode_2696.java
Leetcode_567.java

Solved Leetcode question number 567

Leetcode 567

---

.vscode/launch.json
Leetcode_2696.java

Solved Leetcode question number 2696

Leetcode-2696

---

.vscode/launch.json
Leetcode_1813.java
Leetcode_2696.java

Solved Leetcode question number 1813

Leetcode 1813

---

text_alignment.py

It provides the solution for a popular Hackerrank question called the "Alignment Problem"
Qualified on the Hackerrank website
No
Yes

Solution for Text Alignment Question In Hackerrank

---

binary-to-decimal-conversion.py

What does this PR do?
This PR introduces a Python script that converts a binary number (provided as a string) to its decimal equivalent using Python's built-in int() function.
Test Plan
Run the script and input a binary number (e.g., 1010).
Verify that the output correctly matches the decimal equivalent (e.g., 10 for 1010).
Test with various binary inputs to ensure accurate conversion.
Related PRs and Issues
No related PRs or issues at the moment.
Have you read the [Contributing Guidelines on issues](https://github.com/ghostmkg/programming-language/compare/CONTRIBUTING.md)?
Yes.

Binary To Decimal Converter

---

factorial-of-a-number.py

What does this PR do?
This PR adds a function to calculate the factorial of a given number using an iterative approach. The result is printed to the console.
Test Plan
Enter a positive integer (e.g., 5). Expect output: The factorial of 5 is: 120.
Test with 0. Expect output: The factorial of 0 is: 1.
Input a negative integer (e.g., -3) to ensure graceful handling of invalid inputs.
Related PRs and Issues
None.
Have you read the [Contributing Guidelines on issues](https://github.com/ghostmkg/programming-language/compare/CONTRIBUTING.md)?
Yes.

Factorial of a Number

---

Cube_3D/atm.java

Atm Simulator in java

---

TwoSum.js

feat: #109
- This pull request implements a solution for the "Two Sum" problem using a hash map for efficient lookup of the complement values. The solution has a time complexity of O(n) by iterating through the array only once.
- This solution leverages a hash map (object) to store and retrieve the complement values. This ensures O(1) lookup time, making the overall complexity O(n). Should we explore alternative methods, or is this the optimal approach?
- The solution assumes that exactly one solution exists and that the same element cannot be used twice. Should additional validation be implemented to handle unexpected input, or is this assumption sufficient?

feat(TwoSum): create TwoSum function using javascript

---

Fabo.java

Fibonacci_method

---

ProgramForThreeSum.java

I have created a java program that will help user to find sum of three numbers .
I didn't change any code rather i created a new file
I believe it is not related to any other PR's
Yes

CREATED THE THREE SUM PROGRAM BY USING JAVA

---

Cube_3D/TernaryOperator.java

Ternary Operator using Java

---

sum_of_vectors_using_structure.c

I have added a new .c file that includes code for adding two vectors using structures
yes

added a .c file

---

nqueen.py

This pr contains a python file that implements the solution of the n queen problem using backtracking

Added n queen problem 

---

Java/Leetcode_3110.java
Java/factorial.java

New java dsa

---

Python/Program to Convert Hexadecimal Number to Binary.py

Create Program to Convert Hexadecimal Number to Binary.py

---

Python/Program to convert a binary number to octal.py

Create Program to convert a binary number to octal.py

---

Python/Program to convert a given number to words.py

Create Program to convert a given number to words.py

---

convert a given number to words.py

Create convert a given number to words.py

---

Next_Greater_Element_II.cpp

This PR solve the Leetcode Problem 503 [Next Greater Element II](https://leetcode.com/problems/next-greater-element-ii/)
The problem requires us to find the next greater element for each element in a circular array. Since the array is circular, we need to handle wrapping from the end of the array back to the beginning. A stack-based approach allows us to efficiently keep track of the elements for which we haven't yet found a next greater element.
1. Initialize a result array with -1, which will store the next greater element for each index. If no greater element is found, it remains -1.
2. Use a stack to keep the indices of elements whose next greater element hasn't been found.
3. Traverse the array twice (simulating the circular array) using i % n to handle the wrap-around.
4. For each …

 next greater element II solution in C++ (easy & Efficient)

---

Python/PDFMerger.py

The pull request help people merge their pdf into a single file, it is very useful in large quantities of PDF files.
No code changed, just added a new code that merge pdf files, this file work in a directory and merge any files that ends with an extension of ".pdf".
this PR is related to issued of organizing and automating files.
YES, I did.

added a pdf merger script using python

---

Python/countdown.py

countdown - python

---

Java/transposeOfAMatrix.java

It helps user to find transpose of a given square function
I didn't change any existing file rather i created my own java file with the appropriate code.
No , this pr is not related to any other issue
YES

Making the required program

---

To_do_list.py

This pull request adds a **To-Do List Application** built using **Python** and the **Tkinter** library. The application allows users to:
- **Add new tasks**: Users can input a task and add it to the list.
- **Delete tasks**: Users can select a task from the list and remove it.
- **Mark tasks as complete**: Users can mark tasks as completed, which will display the task with the "(Completed)" tag.
This GUI-based application provides a simple task management solution for users, demonstrating how to build an interactive Python application using Tkinter. 
**How it works**:
- Tasks are added through an entry field and displayed in a listbox.
- Tasks can be deleted by selecting and clicking the delete button.
- Tasks can be marked as complete by selecting and clicking the mark complete button.

Added a To-Do List Application using Python and Tkinter

---

C++/quicksort.cpp

(added a code for performing quicksort in cpp.)
(issue #155 .)

quicksort in cpp

---

JavaScript/colorFlipper/index.html
JavaScript/colorFlipper/script.js
JavaScript/colorFlipper/styles.css

Added the ColorFlipper project in javascript folder
Yes. I've read the Contributing guidelines

Issue #142 fixed

---

C++/Reverse Linked List.cpp
C++/add_two_numbers_linked_list.cpp

Provides the algorithm to reverse a singly linked list using O(1) space
This is an accepted solution to LeetCode question: https://leetcode.com/problems/reverse-linked-list/description/
Yes

Create Reverse Linked List.cpp

---

Solid_Butterfly_list.py

Print a Butterfly Pattern Using Stars
In this code
The first loop prints the upper part of the butterfly.
The second loop prints the lower part.
Each line consists of stars and spaces to create the butterfly shape.
Just run this code, and it will display a butterfly pattern based on the input number of rows!

Solid_Butterfly_list.py

---

Java/TransposeOfAMatrix.java

#139
1.Class Definition: TransposeOfAMatrix implements functionality for transposing a square matrix.
2.Method calculateTranspose: Swaps elements above the main diagonal to transpose the matrix in-place.
3.Main Method: Initializes a square matrix, checks if it's square, and calls the transpose method if valid.
4.Output: Prints the transposed matrix in a formatted manner.

Added code for transpose of a matrix

---

Java/creatingfactorial.java

It helps users to get factorial of a real number .
No
YES

Creating the factorial

---

C++/QuickSort.cpp

Issue solved #155
added QuickSort algorithm to C++

Fix Quicksort Algorithm in C++ #155

---

JavaScript/reverseWordsString.js

Added reverseWord program in AryaKS01 branch

---

Php/reverseNum.php

#Description
This PR includes Php folder with reverse no programme in it.
This programme is tested with the online editor.
Please merge this PR under hacktoberfest-accepted label.

git commit -m "added php folder with reverse no program"

---

volume_area.py

Hey, here i have given the code to find the area of circle using python programming by using simple basic maths.hope you will accept this pr and add hactoberfest label to it

Code to find area of circle

---

volume_area.py

hey sir, here basically we are learning to find the surface area and volume of cuboid using basic maths,
first user will take input and then we are returning the formula for surface area and volume of cuboid..At the end we are printing it to get our required answer.Hope it helps..hope you will accept this pr and add hactoberfest label to it

Code for calculating area and volume of cuboid

---

Java/TrieDataStructure.java

(insert and search operation in trie data structure.)
(issue #124 .)

Creation of Trie Data Structure : Insert and Search

---

Python/add_two_number.py
Python/multiplication_table.py

A multiplication table from 1 to 10, in python.

Multiplicationtable.py

---

Python/add_two_number.py
Python/shuffle_decks.py

Second python code! This shuffles a deck of cards and then takes out 5 cards. Hope you can merge it

Shuffledecks.py

---

leap_year.py
prime_check.py
shortest_possible_path.py

Hey, this is a code to find the shortest possible distance between two points in 2-Dimension. Hope you will consider and merge my PR and add hactoberfest label to it.

Shortest distance in 2-Dimension

---

prime_check.py

Hey there, this is a code for checking prime numbers. Hope you will consider my contribution and merge it. Please add a hactoberfest label to it.

PRIME CHECKER

---

leap_year.py
prime_check.py

Hey, this is a code for checking if a year is leap year or not. Hoping you will consider and merge my PR and add a Hactoberfest label to it.

LEAP YEAR CHECKER

---

FIBONACCI.py
factor_finder.py

Hey there, this is a code for printing the Fibonacci Sequence by taking an input from the user. Hoping you will consider it and merge my pull request.

FIBONACCI SEQUENCE

---

Java/factorial using class.java

Create factorial using class.java

---

calculator.py

Improvements:
1.	User-friendly prompts: Clear prompts guide the user through the process with easy-to-understand language.
2.	Error handling: Ensures only numeric values are accepted, with prompts that ask for valid inputs.
3.	Option to quit: Users can type “exit” at any point to quit the calculator.
4.	Symbolic operation display: It displays the operation symbol (+, -, *, /) in the result for better clarity.
5.	Streamlined re-calculation prompt: After each calculation, the user is asked if they want to perform another calculation, and the program continues based on their input.
This version enhances the usability of your calculator while maintaining the basic functionality.
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified …

Fixed Calculatory Function with Good Scripting also handled the errors.

---

Catalog company OA test/Catalog.java
Catalog company OA test/CatalogTest.java
Catalog company OA test/Product.java

To create a simple catalog company object-oriented test code in Java, you can follow these steps. This example includes a Product class, a Catalog class to manage a list of products, and a test class to demonstrate their functionality.

Catalog test case 

---

Polynomial_addition.c
implementstack.c

Implement stack datastructure in c.

Stack-datastructure

---

Polynomial_addition.c

C code to add two polynomial (user defined)

code to create polynomial addition

---

removeExtraSpaces.cpp

Removing extra spaces from the String.

---

distance_between_points.py
max_integer.py
max_min_digits.py

hey, here we have find the maximum and minimum digits of a number using max min function of python and also making the digits from int to string to find it using python programming.hope to get pr accepted and get hactoberfest label

Code to find the max and min digits of a given number

---

Longest_Happy_String.cpp

This PR solve the Leetcode Problem 1405 Longest Happy String in C++.
Topics Include: Heap, String, Greedy

Solved Longest Happy String in CPP

---

C/single_linkedlist.c

Implements all basic operations of single linked list in C language
Fix: Issue #199 
(Write your answer here.)Yes

Added single linked list

---

C++/FACTORIAL.cpp

Previously when we provide a negative input we get 1 as output which is not correct. Now, We can find factorial of whole numbers and for negative numbers we provide output "Factorial is not defined for negative numbers.". This will give a good impact on users.

Update FACTORIAL.cpp (For negative input)

---

no_of_diagonals.py

hey,here i wrote the python program for finding the number of diagonals of a given polygon of sides n where we use basic maths formula.

code to find the no of diagonals of a polygon

---

Important Questions/MaxHistogramArea.java

This pull request adds a Java solution for the problem "Finding Maximum Area in a Histogram". The program efficiently calculates the maximum rectangular area that can be formed in a histogram using a stack-based approach.
Input:
An array of non-negative integers representing histogram heights hist[].
Output:
The maximum rectangular area in the histogram.
The solution uses a stack to track the indices of histogram bars, efficiently calculating the maximum area with time complexity O(n).
The solution is related to issue #226

Program to Find Maximum Area in A Histogram in Java

---

Important Questions/MajorityElement.java

This pull request adds a Java solution for the problem "Find the Majority Element in an Array". The program uses the Moore Voting Algorithm to efficiently determine the majority element, which appears more than n/2 times in the array.
Input:
An array of non-negative integers nums[] (0 ≤ nums.length ≤ 10^9)
Output:
The majority element or -1 if no majority element exists.
Constraints:
The input array will always have non-negative integers.
The solution efficiently finds a candidate using a counting technique and then verifies if it is the majority element.
This pull request is related to issue #224

Program to Find Majority Element in an Array

---

Important Questions/BitFlipCount.java

This pull request adds a Java solution for the problem "Count the number of bits to flip to convert a to b". Given two non-negative integers a and b, write a Java program to count how many bits need to be flipped to convert a to b.
Input:
Two non-negative integers a and b (0 ≤ a, b ≤ 10^9)
Output:
The number of bits that need to be flipped to convert a to b.
Constraints:
The input numbers will always be non-negative integers.
The solution uses the XOR (^) operator to find differing bits and applies the bitwise & (n-1) operation to clear the rightmost set bit, counting the flips required.
The solution is related to issue #222

Program to Count Bits to Flip for Number Conversion

---

Important Questions/CountBit.java

This pull request adds a Java solution for the problem "Count all set bits of a number". Given a non-negative integer n, write a Java program to count the number of set bits (1's) in the binary representation of the number.
Input:
A single non-negative integer n (0 ≤ n ≤ 10^9)
Output:
The number of set bits in the binary representation of n
Constraints:
The input number will always be a non-negative integer.
We use a bitwise operation n = n & (n - 1) that clears the rightmost set bit until the number becomes zero. Each time this operation is performed, we increment a counter, making the approach efficient with time complexity proportional to the number of set bits.
The solution to this problem is related to issue #220

Program to Count Set Bits in a Number

---

Python/hollow_diamond_alphabets.py

Add the hollow_diamond_alphabet function, which prints a hollow diamond pattern using uppercase alphabet characters based on the specified size. The parameter n determines the number of rows in the diamond. This function uses spaces for alignment and hollow spaces within the diamond structure, creating a visually appealing output.
Example: For n=5, the output will be:
Yes
Could you please provide hacktoberfest and gssocs tags.

Create  hollow_diamond_alphabets.py

---

PalindromeChecker.py
Prime_in_range.py

Hey there I have written a code to find prime numbers in range which uses  a frequency array to find prime numbers efficiently within specified range . As part of Hacktoberfest 2024, I kindly request you to review this PR and accept it with Hacktoberfest tag and merge it with the original repository . Thank you for your time and consideration!

Prime Number Generation with Frequency Array

---

tailhead

roshankumar

---

Java/Kth Smallest Amount With Single Denomination Combination.java

This PR solve the Leetcode Problem 3116  Kth Smallest Amount With Single Denomination Combination in Java.
Topics Include: Array, Binary Search, Bit Manipulation.
@ghostmkg please merge this Pr by adding hacktoberfest-accepted label

Solved Kth Smallest Amount With Single Denomination Combination in Java

---

Rust/binary-search.rs

This pull request introduces a binary search algorithm implementation in Rust. The function efficiently searches for a target value in a sorted array and returns the index of the target if found.
- Implemented the `binary_search` function that takes a sorted array and a target value as inputs.
- The function utilizes an iterative approach with a time complexity of O(log n).
- Added a simple test case to demonstrate the functionality.

binary-search-in-rust

---

Python/kadane.py

Implemented the Kadane algorithm to solve maximum subarray sum problem using python.
arr = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
result = kadane(arr)
print("Result", result) 6
This pull request will solve and closes #247 
yes I have read Contributing Guidelines on issues

implemented kadane algorithm in python

---

Python/Website_blocker.py

Website Blocking:
- Enhances productivity by allowing users to block distracting websites.
- Provides a focused digital environment during critical work hours.
Website Blocker is made to block the distractions of people as there are certain websites which consumes times but is not productive, So to stop that this is made.
You can give the URL and then the start time/date and end time/date which will block it and then unblock the website till your desired time.
Yes

Website_blocker.py

---

Python/healthy_eyes.py

Eye Health Reminder Timer:
- Promotes eye health during prolonged screen usage.
- Users can set intervals for reminders, encouraging breaks to       rest their eyes.

healthy_eyes.py

---

Python/flashcards.py

This PR introduces a Flashcard App built using Python and Tkinter. The app allows users to:
Add new flashcards (term and definition).
View all flashcards.
Quiz themselves on the flashcards with random questions.
This project demonstrates a simple, user-friendly way to manage flashcards for study purposes. It also provides a graphical interface to make the interaction smooth and intuitive.
To verify the functionality of the Flashcard App, I performed the following tests:
Adding Flashcards: Tested by adding multiple terms and definitions to ensure data was stored correctly.
Viewing Flashcards: Verified that all stored flashcards could be viewed in a structured format.
Quiz Feature: Tested the random quiz functionality to ensure the term and definition were queried correctly and responses …

flashcard app

---

Java/Number of Ways to Rearrange Sticks With K Sticks Visible.java

This PR solve the Leetcode Problem 1866 Number of Ways to Rearrange Sticks With K Sticks Visible in Java.
Topics Include: combinatorics, Math, Dynamic Programming.
@ghostmkg please merge this Pr by adding hacktoberfest-accepted label

Solved Number of Ways to Rearrange Sticks With K Sticks Visible in Java

---

Python/prime numbers in range

find prime numbers in range(a,b)

---

Python/CompoundInterest.py

Compound Interest Calculator

---

Python/hollow increasing triangle

pattern printing in loops hollow right increasing triangle

 hollow increasing triangle pattern

---

Python/hollow hourglass pattern

 hollow hourglass pattern

---

C++/Insertion sort in c++

Complete Insertion sort with algorithm and code implementation In c++

Complete Insertion sort with algorithm and code implementation In c++

---

Cube_3D/BubbleSort.java
Cube_3D/Patterns.java

These are Different Patterns

---

sum_of_factorials.py

Hey there in this PR I have written a code to find sum of factorials of numbers from specified range which takes two integers as input and prints sum of factorials of numbers in between that numbers both inclusive . I hope you will merge this with original branch of your repo . Also add a Hacktober fest tag to this PR . Thankyou for your time.

Sum of factorials from A to B

---

Java/Adventure_game.java

Description:
Improved input validation to handle invalid choices more gracefully. Added detailed error messages to guide players to select a valid option (1, 2, or 3). Enhanced the user experience by making the game more intuitive and responsive to incorrect inputs.
This PR improves input validation in the Dungeon Adventure game by adding clearer error messages for invalid user inputs. It guides players to select a valid option (1, 2, or 3) when making a decision in the game, enhancing the overall user experience.
Changes Made:
1) Added a detailed message when the player enters an invalid choice, prompting them to choose a valid option.
2) Improved the code structure for handling user input, ensuring that the game continues smoothly without breaking when 
an invalid input is detected.
3) …

Enhance input handling in Dungeon Adventure game

---

Word Guessing Game

Word Guessing Game

---

Guessing Game

 Guessing Game

---

Java/Maximal Square.java

This PR solve the Leetcode Problem 221 Maximal Square in Java.
Topics Include: Array, Matrix, Dynamic Programming.
@ghostmkg please merge this Pr by adding hacktoberfest-accepted label

Solved Maximal Square in Java

---

Python/Area and Perimeter of a Rectangle

This pull request finds the area and perimeter of a rectangle.
I made and tested the code in a coding website to ensure that the code is free of errors, and then I copied it over here.
Yes, I have read it.

Create Area and Perimeter of a Rectangle

---

Java/N_Queens.java

This pull request implements a solution to the N-Queens problem, a classic algorithmic challenge that involves placing N queens on an N x N chessboard such that no two queens threaten each other. The solution uses a backtracking approach to explore all possible configurations.

Created N_Queens.java

---

Compound_interest_calculator
perfect_num_checker.py

Hello , I have written a code to check if the given number is perfect or not . A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. I hope you will accept this PR and merge this with your repository , please add hacktober fest tag to the PR . Thankyou!

Perfect number checker

---

Compound_interest_calculator

Hey I have written a code to calculate Compound Interest in this PR which uses arithematic operations to calculate CI  and prints a number rounded upto 2 decimal places , I request you to review this and hope you will merge this with your repository . As the part of Hacktober Fest 2024 accept this PR with Hacktober Fest tag/badge . Thankyou for your time!

Calculate Compound Interest

---

Python/Area of a Circle

FYI: I messed up when creating new files so you may see this file in one branch and in another. This also happened with my simple interest file. So sorry!!
This pull request finds the area of a circle given the radius.
I tested this code in a coding website and then I copied it over here.
Yes I have read it.

Create Area of a Circle

---

Python/Simple Interest Calculator

This pull request finds the simple interest of a loan given the principle, time, and rate of interest.
I tested my code on a coding website, then i copied it to githug,
Yes, I have read it.

Create Simple Interest Calculator

---

Java/burningTree.java

This PR solves the issue no. #289.
IN this I have solved the question Burning Tree which is a hard level question as mentioned in geeksForgeek.
yes, I have read them and done everything accordingly.

burning tree problem

---

Python/Adding Two Numbers
Python/Checking Prime Numbers
Python/Finding Area of a Circle
Python/Simple Interest

This pull request adds a file to the branch that checks if a number inputted by the user is a prime number or not.
I tested my code my using a coding website and copied my code to github.
Yes i have.

Baguette28   1

---

Python/Vampire Tester

Added program Vampire Tester to Python folder
Adds the program Vampire Tester into the PYthon folder
I tested my code in another program
Yes

Create Vampire Tester

---

Simple Snake Game in Python

Simple Snake Game in Python
Install the necessary module: The turtle module is included in the Python standard library, so you don't need to install anything extra.

Create Simple Snake Game in Python

---

C/bubbleSort.c

This PR adds the implementation of the Bubble Sort algorithm in C language. The Bubble Sort algorithm is a simple sorting algorithm that repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. This implementation serves as a foundational example of sorting algorithms for learners and developers.
The Bubble Sort function accepts user input for the number of elements and the elements themselves. Users can test the sorting functionality by providing different sets of integers as input. The program prints the sorted array to verify that the sorting works correctly. 
The sorting can be validated with various input scenarios, including:
- Randomly ordered integers
- Already sorted integers
- …

Added Bubble sort algorithm

---

Josephus Problem

Josephus Problem

---

Python/created a Flashcard Quiz app in python

A simple quiz application that tests the user on flashcards with questions and answers stored in a dictionary.

Create created a Flashcard Quiz app in python

---

Python/Random Quote Generator with Online API

Implemented a Python script that fetches random quotes from the Quotable API. The script makes an HTTP request, retrieves a random quote, and prints it with the author's name. Variable names have been written to mimic human-readable format.

Added random quote generator using online API

---

Python/3 digit anagram.py

this code returns if two no in a line are anagram or not. Two numbers are considered anagrams if the digits of one can be rearranged to form the other number. For instance, 123 and 321 are anagrams, but 123 and 322 are not.

Create 3 digit anagram.py

---

Python/Hangam_Game

Thank you for reading my PR! Please accept as soon as possible. 

DemonLove520 Hangman Game

---

DSA/Alphabet Patterns.cpp

add Alphabet patterns

---

Java/Leetcode_122.java

It includes the addition of a solved leetcode problem (122) in java.
Yes

(add): Leetcode 122 (Best time to buy and sell stock II) problem codein Java

---

C++/recursion.cpp

Implemented recursion in c++ by using example of power function

Created Recursion Implementation

---

Python/Duck Duck Goose

Created program Duck Duck Goose in Python folder
Adds Duck Duck Goose Program to Python folder
I tested my program in another website
Yes.

Create Duck Duck Goose

---

DSA/Reverse_LinkedList

code for reversing Linkedlist in c++

Reversed a Linkedlist

---

DSA/Cycle_detection_Graph.cpp

Implemented cycle detection in graph using BFS

Created Cycle Detection in Graph

---

DSA/Topological Sort

Implemented Topological sort in graphs using DFS with complete explanation and comments

Implemented Topological Sort

---

DSA/Detect_loop_Linkedlist

Added code for detecting Loop in a linked list

Detect Loop in Linkedlist

---

Python/Team Story

Adds program Team Story to Python folder
I tested my program on another website
Yes.

Create Team Story

---

Python/email_validator.py

A simple program that checks if an email address is valid by applying basic regex patterns.

Created email_validator.py

---

Python/random_joke_generator.py

A simple program that fetches random jokes from an online API and displays them.

Created random_joke_generator.py

---

Python/conway-game.py

conways game of life in python

conways game of life

---

JavaScript/BubbleSort.js

Adds a simple javascript implementation of Bubble Sort

JS bubble sort

---

C++/bubblesort.cpp
C++/counting _sort.cpp
C++/dnf.cpp
C++/heap_sort.cpp
C++/quicksort.cpp
C++/selectionsort.cpp
C/countsort.c
C/radixsort.c

Create counting _sort.cpp

---

C/r1.c

I created a new c programm,named creater1.c

---

DSA/Queue_using_stack.cpp

Implemented queue using stack

---

DSA/Height_binary_tree.cpp

Implemented height of binary tree

Implemented height of binary tree

---

DSA/Trapping_Rainwater

Implemented Trapping rainwater problem

Implemented Trapping rainwater problem

---

DSA/subarray_minimum

implemented minimum subarray sum

Implemented Minimum subarray sum

---

DSA/Next_smaller_element

Implemented next smaller element using stack

Implemented next smaller element

---

DSA/Next_Greeater_Element

Implemented Next Greater Element using stack

Implemented Next Greater Element Using Stack

---

DSA/Starting_of_LL

implemented code for starting point of Linkedlist

Starting point of LinkedList

---

DSA/Pallindrome_linkedlist

created code for checking whether linkedlist is pallindrome or not

check pallindrome linkedlist

---

Python/isomorphic_strings

determines if two strings are isomorphic
Input                         Result
1. Mud, Bud                   True
2. cook, seem               True
3. Pull Skull                   False   
4. Dad, dab                   False
5. Beet, Boot                True
yes.

Can a string be converted to another

---

Python/merge_sorted_arrays.py

This program merges two sorted arrays. These arrays are sorted in ascending order.
Input                                 Result
1. [1 2 3 4] , [4 5 6]           [1 2 3 4 4 5 6]
2.  [1 3 5 7], [2 4 6]           [1 2 3 4 5 6 7]
3. [ 4 5 6] [1 2 3]               [1 2 3 4 4 5 6]
4. [4] [1 3 5 7]                   [ 1 3 4 5 7]
yes

Merge Sorted Arrays

---

Python/valid_parentheses.py

this function checks for valid / missing parentheses in a given mathematical expression
Input                     Result
1.    4 + (3 * 7)                      True
2.    4 + 3 * 7)                       False
3.    3 + [ 24 + (3x + 2)        False  
4.    [3 + 2 ( 3  + 4 ) ]           True
5.   {}                                     True    
6.   } {                                    False
yes

Check for missing Parentheses

---

C++/insertionSort.cpp

Resolve issue#276
Please accept under Hacktoberfest2024

Create InsertionSort in C++

---

hourglass.py

hey, here i tried to print an hourglass pattern of number using python programming..hope to get the pr accepted soon and please give the hacktoberfest label

code to print hourglass pattern

---

firstandsecmax.py

hey! in this python code i have coded the logic to find the sum of all even numbers. I'm hoping to get the pr accepted and get the hacktoberfest level.

code to print the sum of all even numbers

---

firstandsecmax.py
sum_of_even_num

hey! in this code i have coded the logic to find the type of triangle . i hope to get the pr accepted and get the hacktober level.

python code to find the type of triangle

---

firstandsecmax.py
reverse
sum_of_even_num

hey! In this code i have written the code to print hollow butterfly. i'm hoping to get the pr accepted and get the hacktoberfest level.

code to print out hollow butterfly

---

evenlydivisiblenum.py
totaldays.py

here i made the code to Find the smallest positive number that is evenly divisible by all numbers between 1 to N(inclusive)...hope to get the pr accepted and get the hacktoberfest label..thank you

code to Find the smallest positive number that is evenly divisible by all numbers between 1 to N(inclusive)

---

totaldays.py

here , i made a program print total number of days in a month using switch case...hope to get pr accepted and get the hacktoberfest label

a program print total number of days in a month using switch case

---

Animal.java
Buyer.java
Course.java
Date.java
Dealer.java
Faculty.java
Invoice.java
MaintainFinance.java
Person.java
Seller.java
Student.java
StudentTest.java
assignmentTest.java

dealer management system

---

butterflypattern.py
countbytitle.py

hey here wrote the code to print Butterfly Pattern. Hope to get the pr accepted and please give the hacktoberfest label.

Code to Print Butterfly Pattern

---

countbytitle.py

hey !! here I wrote the code that allows users to find out how many books have the given title using python programming.
Hope to get the pr accepted and Please give the Hacktoberfest label.

code that allows users to find out how many books have the given title

---

simplepairdproduct.py

here i tried to solve a little complex problem through easy python programming..the problem is as : Given an sequence of N number (N is always even), you need to output a new list with (N/2) numbers where each number represents the pair-wise product of consecutive elements of the array A. In simple terms output (A[0]*A[1]), (A[2]*A[3]), ..., (A[N-2]*A[N-1])....i have attached the best way to solve it..hope to get pr accepted and get the hacktoberfest label..

code to output N/2 elements representing the pairwise product of adjacent elements in the list.

---

Matchstick game winning position pattern

program to print matchstick game winning and losing  position pattern.

Matchstick game winning and losing  position pattern.

---

Tic-Tac-Toe_game

It is the program to play tic-tac-toe in python.

Tic-Tac-Toe_game

---

Armstrong Number

Objective: Determine if a given integer 𝑁 N is an Armstrong number.

Create Armstrong Number

---

Function Distributing Money

Mahesh wants to distribute money (amount K) among his three sisters such that they all end up with the same total amount of money.
No
Yes

Function (Distributing Money)

---

avarage_num_of_3numbers.py
cube_in_range.py

hey this is the code to find cube in range. hope to get pr accepted and get the hacktoberfest label.

cube in range

---

avarage_num_of_3numbers.py

hey !! this is the code to find the average of three numbers. hope to get the pr accepted and please give the hacktoberfest label.

average of 3 number

---

loopforsquarerange.py

here i wrote the code to print the range of squares of numbers within a range.hope to get pr accepted and get the hacktoberfest label

loop square range of numbers

---

hour glass patter.py

this code makes hour glass patter according to the number provided

Create hour glass patter.py

---

swap first and last digit of a number.py

this program swaps the first and last digit of your number. for ex:- if your num is 12345 it will swap 1 and 5, giving the result 52341

Create swap first and last digit of a number.py

---

Crypto dashboard python/cryp.py

I built a Python-powered crypto dashboard that pulls live data from the CoinGecko API, updating prices every 5 seconds.

Crypto dashboard python

---

LinkedIn Web-Design

This is a html-Css code which make the template like your linkedIn profile.

Create LinkedIn Web-Design

---

swapping first two digits

this program can swap first two digits of any number

Create swapping first two digits

---

two_mountain_pattern.py

hey this is the code that prints hollow right angle triangle. hope to get the pr accepted and please give me the hacktobesrfest label.

code that prints hollow right angle triangle

---

two_mountain_pattern.py

hey this is the code to print two mountain parallel . hope to get pr accepted and get the hacktoberfest label.

code that prints two mountains parallel

---

two_mountain_pattern.py

hey this is the code that prints hollow two mountain pattern. hope to get pr accepted and get the hacktoberfest label.

code that prints hollow two mountain pattern

---

two_mountain_pattern.py

hey this is the code that print right pascal triangle. hope to get pr accepted and get the hacktoberfest lable.

code that print right pascal triangle

---

checking leap year or not

this program will help u checking that the given year is leap or not

Create checking leap year or not

---

Java/PrimeChecker.java
Java/prime.java
javascript/code.js
javascript/prime.js

Added Two Sum problem code

---

hollow_reverse_pyramid.py

hey this is the code that prints numbered butterfly.  hope to get pr accepted and get the hacktoberfest label.

code that prints numbered butterfly

---

hollow_reverse_pyramid.py

hey this is the code that print hollow reverse pyramid. hope to get pr accepted and get the hacktoberfest label

code that print hollow reverse pyramid

---

Women sopping webpage

This is a webpage for women shopping site , which includes navigation tags , hyperlinks , buttons , and css styling

Create Women shopping webpage

---

javascript/bubbleSort.js
javascript/factorial.js
javascript/fibonacci.js
javascript/linearSearch.js

- `linearSearch.js`: Simple search through an array
- `bubbleSort.js`: Basic sorting algorithm
- `fibonacci.js`: Recursive Fibonacci generator
- `factorial.js`: Calculates factorial of a number

Added dsa programs in JavaScript

---

C++/BuyAndSellStock.cpp
C++/binary_to_decimal.cpp
hoffmanncoding.java

This PR addresses critical bugs, syntax errors, and performance issues across multiple files in the programming-language repository. All changes maintain backward compatibility while significantly improving code reliability and efficiency.
- **hoffmanncoding.java**: Fixed edge case where single character input would generate empty Huffman codes
- **BuyAndSellStock.cpp**: Fixed missing closing brace causing compilation failure
- **binary_to_demical.cpp**: Fixed filename typo (`demical` → `decimal`)
- **hoffmanncoding.java**: Added null/empty input validation for encode/decode methods
- **BuyAndSellStock.cpp**: Optimized space complexity from O(n) to O(1) while maintaining O(n) time
- **binary_to_decimal.cpp**: 
- Upgraded from `int` to `long long` for 64-bit number support
- Added overflow …

Fix critical bugs and improve code quality across Java and C++ implementations

---

C++/atoi.cpp
Java/Atoi.java
Python/atoi.py
javascript/atoi.js

Add atoi implementations in C++, Java, JavaScript, and Python
- Handle leading whitespace and optional sign
- Convert digits until first non-digit character
- Basic versions without overflow or error checks

Added atoi program

---

Python/sort_list.py

I have added Tim Peters’ Sort algorithm simpler version, it sorts an list in O(_nlogn_) in python

Added timsort (default sort) sorting algorithm in python

---

Python/numpy_mathTutorial.py

Added Python/numpy_mathTutorial.py — a short, student-style NumPy example that demonstrates basic array arithmetic.
It shows 1D and 2D array creation, scalar and element-wise operations (+ - * / ** %), matrix multiplication with np.dot, element-wise matrix multiplication, and a brief float-division example. The script prints outputs to the console so learners can run it and see results immediately. 
python3 Python/numpy_mathTutorial.py
This contribution is respectfull and  I agree to abide by the [Code of Conduct](https://github.com/ghostmkg/programming-language/blob/main/CODE_OF_CONDUCT.md). 
Hacktoberfest2025!

feat: add NumPy array operations and math functions tutorial

---

Python/heap_sort.py
Python/merge_sort.py
Python/quick_sort.py

This pull request adds three common sorting algorithms implemented in Python for DSA practice:
- Quick Sort
- Merge Sort
- Heap Sort
Each algorithm is placed in its own file under the Python/ directory.

Added Python implementations for Quick Sort, Merge Sort, and Heap Sort

---

.vscode/c_cpp_properties.json
.vscode/launch.json
.vscode/settings.json
Java/ArmstrongNumber.java
Java/HeapSort.java
Java/ParenthesisChecker.java

This program checks whether a given string of 
*               parentheses/brackets/braces is balanced or not.

Parenthesis Checker in Java
